print("=" * 45)
print("        FORM INPUT BIODATA MAHASISWA       ")
print("=" * 45)

npm     = input("Masukkan NPM     : ")
nama    = input("Masukkan Nama    : ")
kelas   = input("Masukkan Kelas   : ")
jurusan = input("Masukkan Jurusan : ")
alamat  = input("Masukkan Alamat  : ")
hobby   = input("Masukkan Hobby   : ")

print()
print("=" * 45)
print("           DATA BIODATA MAHASISWA          ")
print("=" * 45)
print(f"  NPM      : {npm}")
print(f"  Nama     : {nama}")
print(f"  Kelas    : {kelas}")
print(f"  Jurusan  : {jurusan}")
print(f"  Alamat   : {alamat}")
print(f"  Hobby    : {hobby}")
print("=" * 45)
print("         Data Berhasil Disimpan!           ")
print("=" * 45)